name: "\U0001F41E Report a problem"
description: 'Report an issue with CLI'
title: 'Bug: (fill in)'
labels:
    - bug
body:
    - type: textarea
      attributes:
          label: What did you do?
          description: |
              Please include a *minimal* reproduction case. Otherwise, include source code, configuration file(s), and any other information about how you're using CLI. You can use Markdown in this field.
          value: |
              <details>
              <summary>Configuration</summary>
              ```
              <!-- Paste your configuration here -->
              ```
              </details>
      validations:
          required: true
    - type: textarea
      attributes:
          label: What did you expect to happen?
          description: |
              You can use Markdown in this field.
      validations:
          required: true
    - type: textarea
      attributes:
          label: What actually happened?
          description: |
              Please copy-paste the actual CLI output. You can use Markdown in this field.
      validations:
          required: true
    - type: checkboxes
      attributes:
          label: Participation
          options:
              - label: I am willing to submit a pull request for this issue.
                required: false
    - type: textarea
      attributes:
          label: Additional comments
          description: Is there anything else that's important for the team to know?
