name: Integration

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    depcheck:
        name: Depcheck

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.12.1
                  package-manager: pnpm
                  package-manager-version: 7.19.0

            - name: Test Depcheck
              run: pnpm depcheck

    inflint:
        name: Inflint

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.12.1
                  package-manager: pnpm
                  package-manager-version: 7.19.0

            - name: Test Inflint
              run: pnpm inflint

    typescript:
        name: TypeScript

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.12.1
                  package-manager: pnpm
                  package-manager-version: 7.19.0

            - name: Test TypeScript
              run: pnpm type-check

    prettier:
        name: Prettier

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.12.1
                  package-manager: pnpm
                  package-manager-version: 7.19.0

            - name: Test Prettier
              run: pnpm prettier

    eslint:
        name: ESLint

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.12.1
                  package-manager: pnpm
                  package-manager-version: 7.19.0

            - name: Test ESLint
              run: pnpm lint

    build:
        name: Build

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.12.1
                  package-manager: pnpm
                  package-manager-version: 7.19.0

            - name: Test build
              run: pnpm build
